### ISSUE TITLE
404 returns on the user specific pages if the user isn't logged in!

### ISSUE THREAD

**Issue by TheImperialEmperor** [TheImperialOne/x-beat#2]
The pages like, Orders, Wishlist, Gift Cards, etc return 404 page. Rather it should take you to login screen or those links shouldn't be visible at all.

**Comment by animeshjare26** [comment]
Issue Title:
Unauthorized access to user-specific pages leads to 404 errors.

Issue Description:
Currently, when a user tries to access user-specific pages without being logged in, they receive a 404 error. The application doesn't check if the user is authenticated before rendering these pages. A proper solution would involve protecting these routes and redirecting unauthenticated users to the login page, rather than allowing them to access pages that they shouldn't.
